/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summonerinfinitysecret;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import static summonerinfinitysecret.Global.P1Vida;

/**
 *
 * @author Christhian
 */
public class StageScreen extends javax.swing.JFrame {

    /**
     * Creates new form StageScreen
     */
    public StageScreen() {
        initComponents();
        hp_1.setValue(0);
        hp_2.setValue(0);
        
         // new animationAndRepainting().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1Char = new javax.swing.JLabel();
        P2Char = new javax.swing.JLabel();
        LifeP1 = new javax.swing.JTextField();
        LifeP2 = new javax.swing.JTextField();
        AttackP1 = new javax.swing.JTextField();
        AttackP2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hp_1 = new javax.swing.JProgressBar();
        hp_2 = new javax.swing.JProgressBar();
        jTextField1 = new javax.swing.JTextField();
        buttonAttP12 = new javax.swing.JButton();
        buttonAttP11 = new javax.swing.JButton();
        buttonAttP22 = new javax.swing.JButton();
        buttonAttP21 = new javax.swing.JButton();
        P2 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1Char.setMaximumSize(new java.awt.Dimension(400, 400));
        P1Char.setMinimumSize(new java.awt.Dimension(400, 400));
        P1Char.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(P1Char, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 167, 209));

        P2Char.setMaximumSize(new java.awt.Dimension(400, 400));
        P2Char.setMinimumSize(new java.awt.Dimension(400, 400));
        P2Char.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(P2Char, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 177, 209));
        getContentPane().add(LifeP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 119, -1));
        getContentPane().add(LifeP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 119, -1));
        getContentPane().add(AttackP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 119, -1));
        getContentPane().add(AttackP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 119, -1));

        jLabel1.setText("HP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel2.setText("HP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel3.setText("ATTACK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel4.setText("ATTACK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        hp_1.setForeground(new java.awt.Color(50, 251, 9));
        hp_1.setMaximum(0);
        hp_1.setToolTipText("");
        hp_1.setStringPainted(true);
        getContentPane().add(hp_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, -1));

        hp_2.setForeground(new java.awt.Color(50, 251, 9));
        hp_2.setMaximum(0);
        hp_2.setToolTipText("");
        hp_2.setStringPainted(true);
        getContentPane().add(hp_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 150, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 220, -1));

        buttonAttP12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAttP12MouseReleased(evt);
            }
        });
        getContentPane().add(buttonAttP12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, 30));

        buttonAttP11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAttP11MouseReleased(evt);
            }
        });
        getContentPane().add(buttonAttP11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 30));

        buttonAttP22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAttP22MouseReleased(evt);
            }
        });
        getContentPane().add(buttonAttP22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 190, 30));

        buttonAttP21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAttP21MouseReleased(evt);
            }
        });
        getContentPane().add(buttonAttP21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 190, 30));

        P2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/01010101.png"))); // NOI18N
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/01010101.png"))); // NOI18N
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String namebuttonp11 = Global.NombreAttacP1;
       this.buttonAttP11.setText(namebuttonp11);
       String namebuttonp12 = Global.NombreAttacP12;
       this.buttonAttP12.setText(namebuttonp12);
       
       String namebuttonp21 = Global.NombreAttacP2;
       this.buttonAttP21.setText(namebuttonp21);
       String namebuttonp22 = Global.NombreAttacP21;
       this.buttonAttP22.setText(namebuttonp22);
       
        int lif = Global.P1Vida;
        int att = Global.P1Ataque;
        LifeP1.setText(""+lif);
        AttackP1.setText(""+att);
        hp_1.setMaximum(lif);
        hp_1.setValue(lif);
        if(Global.P1.equals("Mago")){
            P1Char.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/wizard100x1002.png"))); 
        }
            else if(Global.P1.equals("Golem")){
            P1Char.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/golem100x1002.png"))); 
        }
        
        //
        int life = Global.P2Vida;
        int attc = Global.P2Ataque;
        LifeP2.setText(""+life);
        AttackP2.setText(""+attc);
        
        hp_2.setMaximum(life);
        hp_2.setValue(life);
        if(Global.P2.equals("Mago")){
            P2Char.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/wizard100x100.png"))); 
        }
            else if(Global.P2.equals("Golem")){
            P2Char.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpg/ImageToBottons100x100/golem100x100.png"))); 
        }
        
        P1.setVisible(false);
        P2.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void buttonAttP11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAttP11MouseReleased
        int damage = Global.P1Ataque;
        int lifebar = hp_2.getValue();
        LifeP2.setText(""+lifebar);
        int dañorev = 0;
        for(int contador = 0; contador <= lifebar; contador++){
            if(contador<lifebar){
                dañorev = lifebar-damage;
                hp_2.setValue(dañorev);
                Global.P2Vida = dañorev;
                //LifeP2.wait(lifebar);
            }
        LifeP2.setText(""+dañorev);
        }  
        if(Global.P2Vida <= 0){
            String win = "Player 1";
            Global.Winner = win;
            WinScreen va = new WinScreen();
            va.setVisible(true);
            P2Char.setVisible(false);
            this.dispose();
            
        }
        
    }//GEN-LAST:event_buttonAttP11MouseReleased

    private void buttonAttP12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAttP12MouseReleased
        int damage = Global.P1Ataque2;
        int lifebar = hp_2.getValue();
        LifeP2.setText(""+lifebar);
        int dañorev = 0;
        for(int contador = 0; contador <= lifebar; contador++){
            if(contador<lifebar){
                dañorev = lifebar-damage;
                hp_2.setValue(dañorev);
                Global.P2Vida = dañorev;
                //LifeP2.wait(lifebar);
            }
        LifeP2.setText(""+dañorev);
        }  
        if(Global.P2Vida <= 0){
            WinScreen va = new WinScreen();
            va.setVisible(true);
            P2Char.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_buttonAttP12MouseReleased

    private void buttonAttP21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAttP21MouseReleased
        int damage = Global.P2Ataque;
        int lifebar = hp_1.getValue();
        LifeP1.setText(""+lifebar);
        int dañorev = 0;
        for(int contador = 0; contador <= lifebar; contador++){
            if(contador<lifebar){
                dañorev = lifebar-damage;
                hp_1.setValue(dañorev);
                Global.P1Vida = dañorev;
                //LifeP2.wait(lifebar);
            }
        LifeP1.setText(""+dañorev);
        }  
        if(Global.P1Vida <= 0){
            String win = "Player 2";
            Global.Winner = win;
            WinScreen va = new WinScreen();
            va.setVisible(true);
            P1Char.setVisible(false);
            this.dispose();
            
        }
    }//GEN-LAST:event_buttonAttP21MouseReleased

    private void buttonAttP22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAttP22MouseReleased
        int damage = Global.P2Ataque2;
        int lifebar = hp_1.getValue();
        LifeP1.setText(""+lifebar);
        int dañorev = 0;
        for(int contador = 0; contador <= lifebar; contador++){
            if(contador<lifebar){
                dañorev = lifebar-damage;
                hp_1.setValue(dañorev);
                Global.P1Vida = dañorev;
                //LifeP2.wait(lifebar);
            }
        LifeP1.setText(""+dañorev);
        }  
        if(Global.P1Vida <= 0){
            String win = "Player 2";
            Global.Winner = win;
            WinScreen va = new WinScreen();
            va.setVisible(true);
            P1Char.setVisible(false);
            this.dispose();
            
        }
   
    }//GEN-LAST:event_buttonAttP22MouseReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       boolean p1 = Global.P1Turn;
       if (p1){}
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StageScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StageScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AttackP1;
    private javax.swing.JTextField AttackP2;
    private javax.swing.JTextField LifeP1;
    private javax.swing.JTextField LifeP2;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1Char;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P2Char;
    private javax.swing.JButton buttonAttP11;
    private javax.swing.JButton buttonAttP12;
    private javax.swing.JButton buttonAttP21;
    private javax.swing.JButton buttonAttP22;
    public static javax.swing.JProgressBar hp_1;
    public static javax.swing.JProgressBar hp_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
 

}
